### ISSUE TITLE
packagecloud - ERROR: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ctippur** [computology/packagecloud-cookbook#26]
I am trying to install runit (latest version) and it seem to use packagecloud. What am I doing wrong?

Here is the debug info:

==> broker01:  39:  case node['platform_family']
==> broker01:  40:  when 'rhel', 'fedora'
==> broker01:  41:  
==> broker01:  42>>   packagecloud_repo 'imeyer/runit' unless node['runit']['prefer_local_yum']
==> broker01:  43:    package 'runit'
==> broker01:  44:  
==> broker01:  45:    if node['platform_version'].to_i == 7
==> broker01:  46:      service 'runsvdir-start' do
==> broker01:  47:        action [:start, :enable]
==> broker01:  48:      end
==> broker01:  49:    end
...
==> broker01: [2015-09-21T04:02:10+00:00] ERROR: undefined method `[]' for nil:NilClass

I also tried changing it to:
packagecloud_repo "imeyer/runit" do
    type "deb" # or "rpm" or "gem"
 end

I get a diff error
No resource or method named `packagecloud_repo' for `Chef::Recipe "default"'

**Comment by ice799** [comment]
The `ERROR: undefined method `[]'` error seems to be coming from this part of line 42:
```
unless node['runit']['prefer_local_yum']
```

which is part of the runit cookbook, so asking there might answer your question.

The second error you got: 
```
No resource or method named packagecloud_repo' forChef::Recipe "default"'
```

Sounds like you don't have the packagecloud cookbook installed, included, or something else with your local dev environment.

Going to close this issue because as far as I can tell, this is not related to the cookbook itself but the local dev environment or runit.
