### ISSUE TITLE
Opsworks error undefined method 'source_url'

### ISSUE THREAD

**Issue by gkeskarZen** [computology/packagecloud-cookbook#56]
we are using Opsworks running off Chef 11.10, Berkshelf 3.2.0
Recently we started getting following error when we run chef client
[2018-09-07T17:59:45+00:00] ERROR: Could not read /opt/aws/opsworks/current/merged-cookbooks/packagecloud into a Chef object: undefined method `source_url' for #<Chef::Cookbook::Metadata:0x007f3af39e5518>
[2018-09-07T17:59:45+00:00] ERROR: #<NoMethodError: undefined method `to_hash' for nil:NilClass>

It looks like other cookbooks have same issues:
https://github.com/chef-cookbooks/aws/issues/122

Can you please fix this issue...?
reference-https://github.com/mes/squid/commit/f96ade88f0e2d9fd0ea744207029d584dc4a939a

**Comment by itjedi42** [comment]
https://github.com/computology/packagecloud-cookbook/pull/57 <-- this should fix it

**Comment by armandocanals** [comment]
So, the recently merged PR might address this specific error, but it won't make this cookbook work for Chef 11 since it has custom resources requiring Chef 12.5 or higher, as @tas50 pointed out. I'm going to leave the merge in place, but closing out this issue since there's no plan to support Chef 11.
